NetCoreSeguridadEmpleados/Models/Empleado.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace NetCoreSeguridadEmpleados.Models
{
    [Table("EMP")]
    public class Empleado
    {
        [Key]
        [Column("EMP_NO")]
        public int IdEmpleado { get; set; }
        [Column("APELLIDO")]
        public string Apellido { get; set; }
        [Column("OFICIO")]
        public string Oficio { get; set; }
        [Column("SALARIO")]
        public int Salario { get; set; }
        [Column("DEPT_NO")]
        public int Departamento { get; set; }
    }
}

NetCoreSeguridadEmpleados/Models/ErrorViewModel.cs
namespace NetCoreSeguridadEmpleados.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

NetCoreSeguridadEmpleados/Controllers/EmpleadosController.cs
using Microsoft.AspNetCore.Mvc;
using NetCoreSeguridadEmpleados.Filters;
using NetCoreSeguridadEmpleados.Models;
using NetCoreSeguridadEmpleados.Repositories;
using System.Security.Claims;

namespace NetCoreSeguridadEmpleados.Controllers
{
    public class EmpleadosController : Controller
    {
        private RepositoryEmpleados repo;

        public EmpleadosController(RepositoryEmpleados repo)
        {
            this.repo = repo;
        }

        [AuthorizeEmpleados]
        public IActionResult PerfilEmpleado()
        {
            return View();
        }

        public async Task<IActionResult> Index()
        {
            List<Empleado> empleados = await this.repo.GetEmpleadosAsync();
            return View(empleados);
        }

        //[AuthorizeEmpleados]
        //public async Task<IActionResult> Details(int idempleado)
        //{
        //    Empleado empleado = await this.repo.FindEmpleadoAsync(idempleado);
        //    return View(empleado);
        //}

        [AuthorizeEmpleados]
        public async Task<IActionResult> Details(int id)
        {
            Empleado empleado = await this.repo.FindEmpleadoAsync(id);
            return View(empleado);
        }

        [AuthorizeEmpleados]
        public async Task<IActionResult> Compis()
        {
            //RECUPERAMOS EL DATO DEL DEPARTAMENTO DEL CLAIM
            string dato =
                HttpContext.User.FindFirst("Departamento").Value;
            int idDepartamento = int.Parse(dato);
            List<Empleado> empleados = await
                this.repo.GetEmpleadosDepartamentoAsync(idDepartamento);
            return View(empleados);
        }

        [AuthorizeEmpleados]
        [HttpPost]
        public async Task<IActionResult> Compis(int incremento)
        {
            string dato =
                HttpContext.User.FindFirst("Departamento").Value;
            int idDepartamento = int.Parse(dato);
            await this.repo.UpdateSalarioEmpleadosDepartamentoAsync
                (idDepartamento, incremento);
            List<Empleado> empleados = await
                this.repo.GetEmpleadosDepartamentoAsync(idDepartamento);
            return View(empleados);
        }
    }
}

NetCoreSeguridadEmpleados/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using NetCoreSeguridadEmpleados.Models;
using System.Diagnostics;

namespace NetCoreSeguridadEmpleados.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

NetCoreSeguridadEmpleados/Controllers/ManagedController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using NetCoreSeguridadEmpleados.Models;
using NetCoreSeguridadEmpleados.Repositories;
using System.Security.Claims;

namespace NetCoreSeguridadEmpleados.Controllers
{
    public class ManagedController : Controller
    {
        private RepositoryEmpleados repo;

        public ManagedController(RepositoryEmpleados repo)
        {
            this.repo = repo;
        }

        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login
            (string username, string password)
        {
            int idEmpleado = int.Parse(password);
            Empleado empleado = await
                this.repo.LogInEmpleadoAsync(username, idEmpleado);
            if (empleado != null)
            {
                //SEGURIDAD
                ClaimsIdentity identity =
                    new ClaimsIdentity(
                        CookieAuthenticationDefaults.AuthenticationScheme,
                        ClaimTypes.Name, ClaimTypes.Role);
                //CREAMOS EL CLAIM PARA EL NOMBRE (APELLIDO)
                Claim claimName =
                    new Claim(ClaimTypes.Name, empleado.Apellido);
                identity.AddClaim(claimName);
                Claim claimId =
                    new Claim(ClaimTypes.NameIdentifier, empleado.IdEmpleado.ToString());
                identity.AddClaim(claimId);
                Claim claimOficio =
                    new Claim(ClaimTypes.Role, empleado.Oficio);
                identity.AddClaim(claimOficio);
                Claim claimSalario =
                    new Claim("Salario", empleado.Salario.ToString());
                identity.AddClaim(claimSalario);
                Claim claimDepartamento =
                    new Claim("Departamento", empleado.Departamento.ToString());
                identity.AddClaim(claimDepartamento);
                //COMO POR AHORA NO VOY A UTILIZAR NI SE UTILIZAR ROLES
                //NO LO INCLUIMOS
                ClaimsPrincipal userPrincipal =
                    new ClaimsPrincipal(identity);
                await HttpContext.SignInAsync(
                    CookieAuthenticationDefaults.AuthenticationScheme,
                    userPrincipal);
                //LO VAMOS A LLEVAR A UNA VISTA CON LA INFORMACION
                //QUE NOS DEVUELVE EL FILTER EN TEMPDATA
                string controller = TempData["controller"].ToString();
                string action = TempData["action"].ToString();

                
                if (TempData["id"] != null)
                {
                    string id = "";
                    id = TempData["id"].ToString();
                    return RedirectToAction(action, controller, new { id = id });
                }
                else
                {
                    return RedirectToAction(action, controller);
                }
            }
            else
            {
                ViewData["MENSAJE"] = "Usuario/Password incorrectos";
                return View();
            }
        }

        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync
                (CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Index", "Home");
        }

        public IActionResult ErrorAcceso()
        {
            return View();
        }
    }
}

NetCoreSeguridadEmpleados/Views/Empleados/Compis.cshtml
@model IEnumerable<NetCoreSeguridadEmpleados.Models.Empleado>

@{
    ViewData["Title"] = "Compis";
}

<h1 style="color:fuchsia">Compis de Trabajo</h1>

@if (Context.User.IsInRole("PRESIDENTE") == true
|| Context.User.IsInRole("DIRECTOR") == true)
{
    <partial name="_FormUpdateSalarios"/>
}

<table class="table table-bordered table-warning">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.IdEmpleado)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Apellido)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Oficio)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Salario)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Departamento)
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.IdEmpleado)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Apellido)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Oficio)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Salario)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Departamento)
            </td>
        </tr>
}
    </tbody>
</table>

NetCoreSeguridadEmpleados/Views/Empleados/Details.cshtml
@model NetCoreSeguridadEmpleados.Models.Empleado

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Empleado</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdEmpleado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdEmpleado)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Apellido)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Apellido)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Oficio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Oficio)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Salario)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Salario)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Departamento)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Departamento)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>

NetCoreSeguridadEmpleados/Views/Empleados/Index.cshtml
@model IEnumerable<NetCoreSeguridadEmpleados.Models.Empleado>

@{
    ViewData["Title"] = "Index";
}

<h1>Seguridad Empleados</h1>

<table class="table table-bordered">
    <thead>
        <tr>
            <th>ID EMPLEADO</th>
            <th>APELLIDO</th>
            <th>OFICIO</th>
            <th>SALARIO</th>
            <th>DEPARTAMENTO</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.IdEmpleado)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Apellido)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Oficio)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Salario)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Departamento)
            </td>
            <td>
                <a asp-controller="Empleados"
                    asp-action="Details"
                    asp-route-idempleado="@item.IdEmpleado"
                    class="btn btn-info">
                    Details
                </a>
                    <a asp-controller="Empleados"
                       asp-action="Details"
                       asp-route-id="@item.IdEmpleado"
                       class="btn btn-success">
                        Details ID
                    </a>
            </td>
        </tr>
}
    </tbody>
</table>

NetCoreSeguridadEmpleados/Views/Empleados/PerfilEmpleado.cshtml
@using System.Security.Claims

<h1>
    Perfil del Sr/Sra: @Context.User.Identity.Name
</h1>

<ul class="list-group">
    <li class="list-group-item">
        Oficio: @Context.User.FindFirst(ClaimTypes.Role).Value
    </li>
    <li class="list-group-item">
        Salario: @Context.User.FindFirst("Salario").Value
    </li>
    <li class="list-group-item">
        Departamento: @Context.User.FindFirst("Departamento").Value
    </li>
</ul>
<h2>Todos los Claims</h2>
<ul>
    @foreach (Claim claim in Context.User.Claims)
    {
        <li>@claim.Type: <b>@claim.Value</b></li>
    }
</ul>

NetCoreSeguridadEmpleados/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

NetCoreSeguridadEmpleados/Views/Managed/ErrorAcceso.cshtml
<h2 style="color:red">
    No tiene permisos para acceder a esta Zona
</h2>
<img src="~/images/erroracceso.jpg" />s

NetCoreSeguridadEmpleados/Views/Managed/Login.cshtml
<h1 style="color:blueviolet">
    Log In Empleados
</h1>

<form method="post">
    <label>Apellido</label>
    <input type="text" name="username" class="form-control"/>
    <label>Password</label>
    <input type="text" name="password" class="form-control"/>
    <button class="btn-danger">
        Log In
    </button>
</form>
<h2 style="color:red">
    @ViewData["MENSAJE"]
</h2>

NetCoreSeguridadEmpleados/Views/Shared/_FormUpdateSalarios.cshtml
<form method="post">
    <label>Incremento salarial</label>
    <input type="text" name="incremento" class="form-control" />
    <button class="btn btn-info">
        A subir salarios!!!
    </button>
</form>

NetCoreSeguridadEmpleados/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NetCoreSeguridadEmpleados</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/NetCoreSeguridadEmpleados.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/images/deadpool.png" style="width:50px"/>
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-info" 
                            asp-controller="Empleados" asp-action="Index">
                                Empleados
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-danger"
                               asp-controller="Empleados"
                               asp-action="Compis">
                                Compis LAYOUT
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <partial name="_MenuEmpleado"/>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - NetCoreSeguridadEmpleados - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

NetCoreSeguridadEmpleados/Views/Shared/_MenuEmpleado.cshtml
@if (Context.User.Identity.IsAuthenticated == false)
{
    //EFECTO OPTICO DEL LOGIN
    <li class="nav-item">
        <a asp-controller="Empleados"
            asp-action="PerfilEmpleado"
            class="nav-link">
            Log In
        </a>
    </li>
}
else
{
    <li class="nav-item">
        <a asp-controller="Managed"
            asp-action="Logout"
            class="nav-link">
            Log out <span style="color:blue">
                @Context.User.Identity.Name
            </span>
        </a>
    </li>
    <li class="nav-item">
        <a asp-controller="Empleados"
           asp-action="PerfilEmpleado"
           class="nav-link">
            Mi perfil
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-danger"
           asp-controller="Empleados"
           asp-action="Compis">
            Compis
        </a>
    </li>
}